### PR TITLE
Prefix Added For The Naming Convention

### PR DESCRIPTION
**Pull request by harshilpatel984**
Added Prefix For the Naming Convention as per the Microsoft guidance.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-prefix-suffix

### CODE REVIEW

**Comment by StanislawStempin** [comment]
Hi,
Thank you for the contribution. I'm not sure we want to accept it. With this the snippets will have more text but you still have a single placeholder that will be replaced when typing the name. Is it just to remind people to use the prefix? In that case this will be achieved by the AppSourceCop analyzer.

**Comment by harshilpatel984** [comment]
Hi @StanislawStempin ,

I have noticed many times people forget to set  AppSourceCop and forget to use prefix and suffix. It will require more time to check naming conventions of the objects. So, Prefix are must when we are developing objects for the clients. still I feel it is required from the developer's end.

**Comment by ik3ras** [comment]
I suggest adding suffix also

**Comment by harshilpatel984** [comment]
> I suggest adding suffix also

Hi @ik3ras ,

If this change will be merged then I can go for the suffix also. So, We have to wait for the decision.

**Comment by StanislawStempin** [comment]
Since not all the code is being written for AppSource and since adding the text in snippets doesn't really help much beyond reminding about the existance of the prefix I will reject this PR.

You can consider writing a separate VS Code extension that would provide smart snippets with prepopulated prefix but in general we are planning to address this problem using code actions (and long-term by introducing namespaces).

**Pull request closed without merging**
