### PR TITLE
Added Czech language... :-)

### PR DESCRIPTION
**Pull request by kine**

### CODE REVIEW

**Comment by StanislawStempin** [comment]
We would like to merge your contribution but could you please resolve conflicts with the latest version of master branch.

**Comment by markbrummel** [comment]
Should be done. Used number 13

 

Van: Stanislaw Stempin [mailto:notifications@github.com] 
Verzonden: woensdag 30 november 2016 13:58
Aan: Microsoft/AL <AL@noreply.github.com>
Onderwerp: Re: [Microsoft/AL] Added Czech language... :-) (#15)

 

We would like to merge your contribution but could you please resolve conflicts with the latest version of master branch.

**Comment by kine** [comment]
I have merged the master and updated my code.

**Comment by StanislawStempin** [comment]
Please increment the argument for the Random procedure call :)

**Comment by kine** [comment]
Corrected and updated from master.

**Pull request merged**
