### PR TITLE
Improve the readme

### PR DESCRIPTION
**Pull request by Gallimathias**
Update from #257 

Constantly I am looking for relevant info or am asked. So I now add the info myself ;). Also, the readme looks more beautiful now. I find at least XD

### CODE REVIEW

**Comment by SusanneWindfeldPedersen** [comment]
Please move the section about the code of conduct to the bottom of the file. Thx. 
This paragraph:
"This project has adopted the Microsoft Open Source Code of Conduct. For more information see the Code of Conduct FAQ or contact __opencode@microsoft.com__ with any additional questions or comments. "

**Comment by Gallimathias** [comment]
@SusanneWindfeldPedersen  You're right this is so better :)

The pull request is now expected to be up to date.

Should one change this sentence? : 

"We're not yet in preview, so this repo is meant as a way for you to get familiar with the new syntax and provide feedback."

Change to 

"We are currently in the preview and the new developer experience is not yet intended for the productive use, so this repo is meant as a way for you to get familiar with the new syntax and provide feedback."

**Comment by SusanneWindfeldPedersen** [comment]
Super, thanks. I think we should use the "We are currently in the preview and the new developer experience is not yet intended for the productive use, so this repo is meant as a way for you to get familiar with the new syntax and provide feedback." paragraph.

**Comment by Gallimathias** [comment]
Is done. :)

**Comment by SusanneWindfeldPedersen** [comment]
Thanks! Merging your pull request.

**Comment by Gallimathias** [comment]
Wow cool :)

**Pull request merged**
