### PR TITLE
Added Catalan greeting

### PR DESCRIPTION
**Pull request by JosepPages**

### CODE REVIEW

**Comment by StanislawStempin** [comment]
We would like to merge your contribution but could you please resolve conflicts with the latest version of master branch.

**Comment by StanislawStempin** [comment]
The pull request still has conflicts with the master branch and cannot be merged.

**Comment by JosepPages** [comment]
Hi Stanislaw. I think the conflicts has been solved. Thanks.

**Comment by StanislawStempin** [comment]
The conflicts haven't been resolved. You can find more information on how to do it here:
https://help.github.com/articles/addressing-merge-conflicts/

**Pull request closed without merging**
